[package]
name = "lib_jsl_integration"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "../../README.md"
description = "Numerical integration engines for one-dimensional and stochastic integration."

[lib]
path = "src/mod.rs"

[dependencies]
lib_jsl_core = { path = "../core" }
lib_jsl_random = { path = "../random" }
